package interview.guide.modules.interview.websocket;

public enum InterviewEventType {
  DEVICE_READY,
  START_INTERVIEW,
  ANSWER_STARTED,
  ANSWER_SUBMITTED,
  AUDIO_CHUNK,
  READ_QUESTION,
  VIDEO_CHUNK_UPLOADED,
  PAUSE_REQUEST,
  RESUME_REQUEST,
  FINISH_REQUEST,
  PING,
  SESSION_STATUS_CHANGED,
  QUESTIONS_READY,
  QUESTIONS_FAILED,
  NEW_QUESTION,
  QUESTION_AUDIO_READY,
  SPEECH_RECOGNITION_READY,
  ANSWER_TRANSCRIPT,
  ANSWER_ACCEPTED,
  EVALUATION_COMPLETED,
  NEXT_QUESTION_PENDING,
  WARNING_EVENT,
  INTERVIEW_FINISHED,
  PONG,
  ERROR;

  public boolean isClientEvent() {
    return switch (this) {
      case DEVICE_READY, START_INTERVIEW, ANSWER_STARTED, ANSWER_SUBMITTED,
          AUDIO_CHUNK, READ_QUESTION, VIDEO_CHUNK_UPLOADED, PAUSE_REQUEST,
          RESUME_REQUEST, FINISH_REQUEST, PING -> true;
      default -> false;
    };
  }
}
